name: CI Pull Request Checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  cichecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install package
        run: |
          python -m pip install -v .

      - name: Check package is importable
        run: |
          python -c 'import mantid_sphinx_theme'
