name: CI Pull Request Checks

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  cichecks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Pre-commit checks
        uses: pre-commit/action@v2.0.3

      - name: Install package and testing requirements
        run: |
          python -m pip install -v .[test]

      - name: Test suite
        run: |
          python -m pytest . -v
